# AetherOS Live Session (UEFI boot entry)

title   AetherOS Live Session
linux   /aetheros/boot/vmlinuz-linux-lts
initrd  /aetheros/boot/initramfs-linux-lts.img
options archisobasedir=aetheros archisolabel=AETHER_%ISO_LABEL% quiet splash
