# AetherOS Live Session - Safe Mode (UEFI boot entry)

title   AetherOS Live Session (Safe Mode)
linux   /aetheros/boot/vmlinuz-linux-lts
initrd  /aetheros/boot/initramfs-linux-lts.img
options archisobasedir=aetheros archisolabel=AETHER_%ISO_LABEL% nosplash
